

server:
  port: 7000
#链路追踪
spring:
  zipkin:
    sender:
      type: web
    base-url: http://192.168.6.200:9411/


  datasource:
    url: jdbc:mysql://192.168.6.200:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
