server:
  port: 7200
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  zipkin:
    sender:
      type: web
    base-url: http://192.168.6.200:9411/
  redis:
    port: 6379
    password: 123456
    host: 192.168.6.200

app:
  threadpool:
    corePoolSize: 4
    maxPoolSize: 8
    aliveTime: 300
    blocking-queue: 2000

management:
  endpoints:
    web:
      exposure:
        include: "*"
