# profile \u6807\u8BC6
spring:
  shardingsphere:
    datasource:  #\u914D\u7F6E\u6570\u636E\u6E90\u5730\u5740\u7684
      names: master,slave_01,slave_02
      #\u914D\u7F6E\u4E09\u4E2A\u6570\u636E\u6E90
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        # http://192.168.200.1:8888/aaaa?a=b&c=d
        jdbcUrl: jdbc:mysql://192.168.6.200:3306/gmall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456

      slave_01:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.6.200:3307/gmall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456

      slave_02:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.6.200:3308/gmall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456

    rules:
      #\u6307\u5B9A\u8BFB\u5199\u5206\u79BB\u89C4\u5219
      readwrite-splitting:
        data-sources:
          myds: #\u903B\u8F91\u6570\u636E\u6E90
            type: Static
            props:
              write-data-source-name: master
              read-data-source-names: slave_01,slave_02
            load-balancer-name: haha
        load-balancers:
          haha:
            type: ROUND_ROBIN
    props:
      sql-show: true

